test
Signed-off-by: Dorra Jaouad <dorra.jaoued7@gmail.com>

diff --git a/.github/workflows/opengrep-scan.yml b/.github/workflows/opengrep-scan.yml
--- a/.github/workflows/opengrep-scan.yml
+++ b/.github/workflows/opengrep-scan.yml
@@ -13,7 +13,6 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      # Step 2: Download and install OpenGrep
       - name: Install OpenGrep
         run: |
           # Download the OpenGrep binary
@@ -25,20 +24,12 @@ jobs:
           # Move the binary to a directory in PATH
           sudo mv opengrep /usr/local/bin/opengrep
 
-      # Step 3: Define custom rules and run OpenGrep
       - name: Run OpenGrep with custom rules
         run: |
-          # Define your custom rules (e.g., TODO, FIXME, debug statements)
-          RULES="TODO|FIXME|console\.log|print_r|var_dump|API_KEY|PASSWORD|SECRET"
-
-          # Run OpenGrep with the custom rules
-          output=$(opengrep "$RULES")
-
-          # Check if any matches were found
-          if [ -n "$output" ]; then
-            echo "::error::OpenGrep found issues in the codebase:"
-            echo "$output"
-            exit 1  # Fail the workflow if issues are found
-          else
-            echo "No issues found. Codebase is clean!"
+          opengrep --metrics=off --error --include='*.php' --include='*.vue' --include='*.js' --include='*.ts' --exclude-rule='javascript.vue.security.audit.xss.templates.avoid-v-html.avoid-v-html'
+          # If findings are detected (non-zero exit code), fail the step
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "::error::OpenGrep found issues in the code. Check the report for details."
+            exit 1
           fi
